# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HS-menu-delivery' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SnapKit'
  pod 'SwiftGen'
  pod 'SwiftLint'
  pod 'Kingfisher'
  pod 'DropDown'

  # Pods for HS-menu-delivery

  target 'HS-menu-deliveryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HS-menu-deliveryUITests' do
    # Pods for testing
  end

end
